name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Build binary
        run: |
          make
          chmod +x comment-remove
          ls -lah comment-remove

      - name: Install packaging tools
        run: |
          sudo apt-get install -y rpm ruby ruby-dev
          sudo gem install fpm

      - name: Create DEB package
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          mkdir -p debian/usr/bin
          cp comment-remove debian/usr/bin/
          fpm -s dir -t deb \
            -n comment-remove \
            -v $VERSION \
            -C debian \
            --prefix / \
            --architecture amd64 \
            --deb-compression xz \
            --depends "libc6, diffutils" \
            --package "comment-remove_${VERSION}_amd64.deb"
          ls *.deb

      - name: Create RPM package
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          mkdir -p rpmbuild/usr/bin
          cp comment-remove rpmbuild/usr/bin/
          fpm -s dir -t rpm \
            -n comment-remove \
            -v $VERSION \
            -C rpmbuild \
            --prefix / \
            --architecture x86_64 \
            --rpm-compression xz \
            --depends "glibc, diffutils" \
            --package "comment-remove-${VERSION}-1.x86_64.rpm"
          ls *.rpm

      - name: Create PKGBUILD
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          cat > PKGBUILD <<EOL
          # Maintainer: alxluk <sash.luk.2311@gmail.com>
          pkgname=comment-remove
          pkgver=$VERSION
          pkgrel=1
          pkgdesc="CLI tool for removing comments from code"
          arch=('x86_64')
          url="https://github.com/alxluk/comment-remove"
          license=('MIT')
          depends=('glibc' 'diffutils')
          source=("https://github.com/alxluk/comment-remove/releases/download/v\$pkgver/comment-remove-\$pkgver-x86_64.tar.gz")
          sha256sums=('SKIP')

          package() {
            install -Dm755 comment-remove -t "\$pkgdir/usr/bin/"
          }
          EOL
          cat PKGBUILD

      - name: Create source tarball
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          tar czf comment-remove-${VERSION}-x86_64.tar.gz comment-remove
          ls *.tar.gz

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.deb
            *.rpm
            PKGBUILD
            *.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
