name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build binary
        run: cargo build --release

      - name: Install packaging tools
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm ruby ruby-dev
          sudo gem install fpm

      - name: Create DEB package
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          mkdir -p debian/usr/bin
          cp target/release/comment-remove debian/usr/bin/
          fpm -s dir -t deb \
            -n comment-remove \
            -v $VERSION \
            -C debian \
            --prefix / \
            --architecture native \
            --deb-compression xz \
            --depends "libc6, diffutils"

      - name: Create RPM package
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          mkdir -p rpmbuild/usr/bin
          cp target/release/comment-remove rpmbuild/usr/bin/
          fpm -s dir -t rpm \
            -n comment-remove \
            -v $VERSION \
            -C rpmbuild \
            --prefix / \
            --architecture native \
            --rpm-compression xz \
            --depends "glibc, diffutils"

      - name: Create PKGBUILD
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          cat > PKGBUILD <<EOL
          # Maintainer: alxluk <sash.luk.2311@email.com>
          pkgname=comment-remove
          pkgver=$VERSION
          pkgrel=1
          pkgdesc="CLI tool for removing comments from code"
          arch=('x86_64')
          url="https://github.com/alxluk/comment-remove"
          license=('MIT')
          depends=('glibc' 'diffutils')
          source=("https://github.com/alxluk/comment-remove/releases/download/v\$pkgver/comment-remove-\$pkgver-linux-x86_64.tar.gz")
          sha256sums=('SKIP')

          build() {
            tar xzf comment-remove-\$pkgver-linux-x86_64.tar.gz
          }

          package() {
            install -Dm755 comment-remove -t "\$pkgdir/usr/bin/"
          }
          EOL

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.deb
            *.rpm
            PKGBUILD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
